name: Deploy
on:
  push:
    paths:
      - .github/workflows/deploy.yml
      - src/**
  workflow_dispatch:

jobs:
  gh-pages:
    name: Deploy on GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.email "fgrandi30@gmail.com"
      - run: git config --global user.name "Federico Grandi"
      - run: git remote set-url origin https://EndBug:${{ secrets.GITHUB_TOKEN }}@github.com/EndBug/nikzionario.git
      - run: npm i
      - run: npm run deploy
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
