name: Deploy
on:
  push:
    paths:
      - .github/workflows/deploy.yml
      - src/**
  workflow_dispatch:

jobs:
  gh-pages:
    name: Deploy on GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run deploy
        env:
          CI: false
