name: Update data
on:
  schedule:
    - cron: 0 * * * *
  push:
    paths:
      - ./src/**
      - ./scripts/**
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: data
          path: data
      - run: |
          npm i
          npm run update
          cp data.json data/data.json
      - uses: EndBug/add-and-commit@v4
        with:
          add: data.json
          cwd: ./data
          message: ':zap: build: update data file'
